### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by floralfaunal** [jzksnsjswkw/Pusher-rootless#2]
请问一下作者，这个rootless版本如何使用。
使用plaera1n 的rootless模式，ios15.8.2，安装时提示需要依赖rocketbootstrap，网上下载了rocketbootstrap但是安装时又有其他依赖，请问如何操作？

**Comment by jzksnsjswkw** [comment]
使用sileo打开

**Comment by floralfaunal** [comment]
> 使用sileo打开

是使用sileo打开的，提示缺少rocket bootstrap依赖，网上找了一下，没发现有rocketbootstrap的rootless版本。![image](https://github.com/jzksnsjswkw/Pusher-rootless/assets/64194105/d8632997-dc2b-4c0e-978f-d6cba086d71e)

**Comment by jzksnsjswkw** [comment]
添加一下源
https://repo.cypwn.xyz/

**Comment by floralfaunal** [comment]
> 添加一下源
> 
> https://repo.cypwn.xyz/

可以了，谢谢

**Comment by jzksnsjswkw** [comment]
已移除该依赖
