### ISSUE TITLE
安装了没有显示这个软件诶

### ISSUE THREAD

**Issue by stfizer** [jzksnsjswkw/Pusher-rootless#4]
![IMG_7405](https://github.com/user-attachments/assets/a6574ced-abf6-4cf8-b78a-4fe057276d52)
![IMG_7406](https://github.com/user-attachments/assets/e6f3347f-cdf1-4b12-aeb8-a402f98eebc0)
安装完了找不到这个软件，请问要进行什么操作吗

**Comment by jzksnsjswkw** [comment]
在设置里
